[gcp_vms]
benchmark-vm-01 ansible_user=sa_app ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[gcp_vms:vars]
ansible_python_interpreter=/usr/bin/python3
project_id=project-3a51a40b-8c9e-4126-804
zone=asia-southeast1-a
custom_sa=app-least-privilege-sa@project-3a51a40b-8c9e-4126-804.iam.gserviceaccount.com